# Generated by Django 4.2.1 on 2023-10-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coolsite', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images/'),
        ),
    ]
