# Generated by Django 4.2.1 on 2023-11-04 08:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coolsite', '0005_tagpost_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coolsite.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='choice',
            field=models.CharField(choices=[('ML', 'Machine Learning'), ('Web', 'Web Development'), ('Syntax', 'Programming Syntax'), ('Book', 'Book Reviews')], default='Syntax', max_length=10, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(default='images/default_image.jpg', upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время публикации'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
    ]
